DROP TABLE IF EXISTS USER_HIKES;

CREATE TABLE USER_HIKES (
  ID BIGINT PRIMARY KEY auto_increment,
  DATE DATE NOT NULL,
  MILEAGE   DOUBLE NOT NULL,
  ELEVATION INTEGER);
  
DROP TABLE IF EXISTS MOUNTAINS;

CREATE TABLE MOUNTAINS (
  ID BIGINT PRIMARY KEY auto_increment,
  NAME VARCHAR(50),
  ELEVATION INTEGER);
  
DROP TABLE IF EXISTS USER_HIKES_MOUNTAINS;

CREATE TABLE USER_HIKES_MOUNTAINS (
  USER_HIKE_ID BIGINT,
  MOUNTAIN_ID BIGINT,
  foreign key (USER_HIKE_ID ) references user_hikes(ID),
  foreign key (MOUNTAIN_ID ) references mountains(ID) );
  
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
  ID BIGINT PRIMARY KEY auto_increment,
  FIRST_NAME VARCHAR(50),
  LAST_NAME VARCHAR(50),
  USER_NAME VARCHAR(50));
